# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180423_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindicator',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator', unique=True),
        ),
    ]
