# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180425_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
