# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatusmonitor',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
