# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180427_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfollowup',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
