# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
